### PR TITLE
Very basic UI for Upstream Sync with Content Library Blocks

### PR DESCRIPTION
**Pull request by bradenmacdonald**
## Description

Implements https://github.com/openedx/frontend-app-authoring/issues/1338 and part of https://github.com/openedx/frontend-app-authoring/issues/1341 . Depends on https://github.com/openedx/edx-platform/pull/34925 .

This PR displays an icon when content comes from a content library (see on the left):

Screenshot

Or if the link is broken, it says that:

Screenshot

And when an update is available, it displays a working "Update" button

Screenshot

It does not yet have a modal to allow you to accept/reject/preview the changes. This is just a developer tool at the moment.

Note: these icons are temporary - I'm waiting to get the correct icons as SVG.

## Testing instructions

1. Change [this line](https://github.com/kdmccormick/edx-platform/blob/8d704a709dac710155f55745cbc7111b8a55698f/cms/djangoapps/contentstore/xblock_storage_handlers/view_handlers.py#L544) to `link_to_upstream=True,`
2. Copy an XBlock from a content library and paste it into a course.
3. Make changes to the block in the library and test the syncing.

## Deadline

ASAP - before Sumac.

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@kdmccormick FYI. Also: nice work on your PR! You have the data available so nicely, it was trivial to implement this first stab at the UI.

**Comment by bradenmacdonald** [comment]
@rpenido FYI

**Comment by bradenmacdonald** [comment]
I have updated the icons to the ones specified in https://github.com/openedx/frontend-app-authoring/issues/1335

**Comment by kdmccormick** [comment]
Manually merged into https://github.com/openedx/edx-platform/pull/34925

**Pull request closed without merging**
